export interface ICliente {
    id: number,
    nome: string,
    razao_social: string,
    cgc: number,
    rg?: number,
    nasc_data?: number,
    contato: number,
    email: string,
    tipo_contribuicao: number,
    inscricao_estadual: number,
    inscricao_municipal: number,
    endereco: string,
    endereco_num?: number,
    complemento?: string,
    cep: number,
    bairro: string,
    cidade: string,
    uf: string,
    pais: string,
    vendedor_id: number
}